### findHotelById
GET http://localhost:8085/api/v1/hotel/4

### findAllHotels
GET http://localhost:8085/api/v1/hotel/list
    ?page=1
    &size=1

### createHotel
POST http://localhost:8085/api/v1/hotel
Content-Type: application/json

{
  "name": "NewHotel",
  "address": {
    "city": "NewCity",
    "street": "NewStreet",
    "number": "NewNumber"
  },
  "distanceFromCenter": 1111,
  "rating": "4.5",
  "numberOfRating": 55555
}

### updateHotel
PUT http://localhost:8085/api/v1/hotel/4
Content-Type: application/json

{
  "id": 4,
  "name": "UpdatedHotel",
  "address": {
    "city": "UpdatedCity",
    "street": "UpdatedStreet",
    "number": "UpdatedNumber"
  },
  "distanceFromCenter": 2222
}

### deleteHotel
DELETE http://localhost:8085/api/v1/hotel/4
