### userRegistrations
GET http://localhost:8085/api/v1/stat/user/registrations
Authorization: Basic dXNlcjE6dXNlcjE=    # user1:user1 - ROLE_ADMIN
#Authorization: Basic dXNlcjI6dXNlcjI=    # user2:user2 - ROLE_USER
#Authorization: Basic dXNlcjM6dXNlcjM=    # user3:user3 - ROLE_USER
#Authorization: Basic dXNlcjQ6dXNlcjQ=    # user4:user4 - ROLE_USER
#Authorization: Basic dXNlcjU6dXNlcjU=    # user5:user5

### bookings
GET http://localhost:8085/api/v1/stat/bookings
Authorization: Basic dXNlcjE6dXNlcjE=    # user1:user1 - ROLE_ADMIN
#Authorization: Basic dXNlcjI6dXNlcjI=    # user2:user2 - ROLE_USER
#Authorization: Basic dXNlcjM6dXNlcjM=    # user3:user3 - ROLE_USER
#Authorization: Basic dXNlcjQ6dXNlcjQ=    # user4:user4 - ROLE_USER
#Authorization: Basic dXNlcjU6dXNlcjU=    # user5:user5
