version: "3.9"
services:
  database:
    build: docker/postgres
    environment:
      POSTGRES_DB: lesson4protected
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5433
    ports:
      - "5433:5433"
    logging:
      options:
        max-size: 100m
