
rootProject.name = "SpringLearning"

include("app")
include("bookShop")
include("lesson1")
include("lesson2")
include("lesson3")
include("lesson4")
include("lesson5")
include("lesson6")
include("lesson6:order-service")
include("lesson6:order-status-service")
include("lesson7")
include("lesson8")
include("lesson8:lesson4-protected")
include("lesson8:lesson7-protected")
include("util:jdbc")
include("util:time")
include("util:utils")
include("cheat-sheet")
