### findPostById
GET http://localhost:8085/api/v1/post/4
Authorization: Basic dGFndWR1cjp0YWd1ZHVy              # by tagudur:tagudur
#Authorization: Basic bmF0YWxpOm5hdGFsaQ==              # by natali:natali
#Authorization: Basic bmF0YWxpXzEyMzpuYXRhbGlfMTIz      # by natali_123:natali_123
#Authorization: Basic YWRtaW46YWRtaW4=                  # by admin:admin
#Authorization: Basic bmV3VXNlcjpuZXdVc2Vy              # by newUser:newUser

### findPostById
GET http://localhost:8085/api/v1/post/list
#Authorization: Basic dGFndWR1cjp0YWd1ZHVy              # by tagudur:tagudur
#Authorization: Basic bmF0YWxpOm5hdGFsaQ==              # by natali:natali
#Authorization: Basic bmF0YWxpXzEyMzpuYXRhbGlfMTIz      # by natali_123:natali_123
#Authorization: Basic YWRtaW46YWRtaW4=                  # by admin:admin
#Authorization: Basic bmV3VXNlcjpuZXdVc2Vy              # by newUser:newUser

### createPost
POST http://localhost:8085/api/v1/post
Content-Type: application/json
#Authorization: Basic dGFndWR1cjp0YWd1ZHVy              # by tagudur:tagudur
#Authorization: Basic bmF0YWxpOm5hdGFsaQ==              # by natali:natali
#Authorization: Basic bmF0YWxpXzEyMzpuYXRhbGlfMTIz      # by natali_123:natali_123
#Authorization: Basic YWRtaW46YWRtaW4=                  # by admin:admin
#Authorization: Basic bmV3VXNlcjpuZXdVc2Vy              # by newUser:newUser

{
  "title": "newPostTitle",
  "description": "newPostDescription",
  "body": "newPostBody",
  "categories": [1,3]
}

### updatePost
PUT http://localhost:8085/api/v1/post/4
Content-Type: application/json
#Authorization: Basic dGFndWR1cjp0YWd1ZHVy              # by tagudur:tagudur
#Authorization: Basic bmF0YWxpOm5hdGFsaQ==              # by natali:natali
#Authorization: Basic bmF0YWxpXzEyMzpuYXRhbGlfMTIz      # by natali_123:natali_123
#Authorization: Basic YWRtaW46YWRtaW4=                  # by admin:admin
#Authorization: Basic bmV3VXNlcjpuZXdVc2Vy              # by newUser:newUser

{
  "id": 4,
  "title": "updatePostTitle",
  "description": "updatePostDescription",
  "body": "updatePostBody"
}

### deletePost
DELETE http://localhost:8085/api/v1/post/4
#Authorization: Basic dGFndWR1cjp0YWd1ZHVy              # by tagudur:tagudur
#Authorization: Basic bmF0YWxpOm5hdGFsaQ==              # by natali:natali
#Authorization: Basic bmF0YWxpXzEyMzpuYXRhbGlfMTIz      # by natali_123:natali_123
#Authorization: Basic YWRtaW46YWRtaW4=                  # by admin:admin
#Authorization: Basic bmV3VXNlcjpuZXdVc2Vy              # by newUser:newUser
