server:
  port: 8085

logging:
  level:
    root: debug

spring:
  application:
    name: "Lesson-7"
  messages:
    basename: "strings"
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/lesson7?authSource=admin
