server:
  port: 8085

logging:
  level:
    root: debug

spring:
  application:
    name: "Lesson-6-order-service"
  messages:
    basename: "strings"
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaGroupId: "kafka-order-group-id"
    kafkaOrderTopic: "order-topic"
    kafkaOrderStatusTopic: "order-status-topic"
