### findUserById
GET http://localhost:8085/api/v1/user?userId=user-1

### findAllUsers
GET http://localhost:8085/api/v1/user/list

### createUser
POST http://localhost:8085/api/v1/user
Content-Type: application/json

{
  "name": "User-new",
  "email": "user-new@ya.ru"
}

### updateUser
PUT http://localhost:8085/api/v1/user
Content-Type: application/json

{
  "id": "user-1",
  "name": "User-update",
  "email": "user-update@ya.ru"
}
