server:
  port: 8085

logging:
  level:
    root: debug

spring:
  application:
    name: "Lesson-5"
  messages:
    basename: "strings"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5433/lesson5"
    username: admin
    password: admin
    hikari:
      schema: lesson5
  sql:
    init:
      schema-locations: classpath:db/init.sql
      data-locations: classpath:db/data.sql
      #      mode: embedded
      mode: always
  data:
    redis:
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#      ddl-auto: create

app:
  cache:
    caches:
      findDtoByNameAndAuthor:
        expire: 20s
      findAllDtoByCategory:
        expire: 20s
