###
GET http://localhost:8085/api/v1/book/list

###
GET http://localhost:8085/api/v1/book/search?name=A%20Song%20of%20Ice%20and%20Fire&author=George%20R.%20R.%20Martin

### findAllByCategory
GET http://localhost:8085/api/v1/book/list/category?categoryName=Fantazy

###
GET http://localhost:8085/api/v1/book/list/category?categoryName=Science%20fiction

###
GET http://localhost:8085/api/v1/book/list/category?categoryName=History
