### findBookById
GET http://localhost:8085/api/v1/book/15

### findBookByNameAndAuthor
GET http://localhost:8085/api/v1/book/search?name=FirstBook&author=FirstAuthor

### findAllByCategory Fantazy
GET http://localhost:8085/api/v1/book/list/category?categoryName=Fantazy

### findAllByCategory Science fiction
GET http://localhost:8085/api/v1/book/list/category?categoryName=Science%20fiction

### findAllByCategory History
GET http://localhost:8085/api/v1/book/list/category?categoryName=History

### findAllByCategory Drama
GET http://localhost:8085/api/v1/book/list/category?categoryName=Drama

### createBook with exist category
POST http://localhost:8085/api/v1/book
Content-Type: application/json

{
  "author": "SecondAuthor",
  "name": "16Book",
  "category": "History"
}

### createBook with new category
POST http://localhost:8085/api/v1/book
Content-Type: application/json

{
  "author": "FirstAuthor",
  "name": "EleventhBook",
  "category": "Drama"
}

### updateBook update author and name
PUT http://localhost:8085/api/v1/book
Content-Type: application/json

{
  "id": 2,
  "author": "_FirstAuthor",
  "name": "_FirstBook",
  "category": "Fantazy"
}

### updateBook update existed category
PUT http://localhost:8085/api/v1/book
Content-Type: application/json

{
  "id": 2,
  "author": "FirstAuthor",
  "name": "FirstBook",
  "category": "Science fiction"
}

### updateBook update new category
PUT http://localhost:8085/api/v1/book
Content-Type: application/json

{
  "id": 2,
  "author": "FirstAuthor",
  "name": "FirstBook",
  "category": "Drama"
}

###
DELETE http://localhost:8085/api/v1/book/2
