version: "3.9"
services:
  database:
    build: docker/postgres
    network_mode: "host"
    volumes:
      - "~/bookshop-local/postgresql:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    logging:
      options:
        max-size: 100m
