spring:
  application:
    name: "BookShopApp-lesson-3"

  web:
    resources:
      static-locations:
        - "classpath:spring-frontend/"
  thymeleaf:
    prefix: "classpath:spring-frontend/"

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/bookshop"
    username: admin
    password: admin
  sql:
    init:
#      schema-locations: "classpath:db/init.sql"
#      data-locations:
#        - "classpath:db/data/data-authors.sql"
#        - "classpath:db/data/data-books.sql"
      mode: never
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${bookshop.db.schema}
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    parameters:
      bookshop.db.schema: ${bookshop.db.schema}

  #    default-schema: ${bookshop.db.schema}


  messages:
    basename: "values.strings.strings"

server:
  port: 8085

logging:
  level:
    root: info

bookshop:
  db:
    schema: "shop"
