version: "3.9"
services:
  database:
    build: docker/postgres
    environment:
      POSTGRES_DB: lesson5
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5433
    ports:
      - "5433:5433"
    logging:
      options:
        max-size: 100m
  redis:
    image: redis:7.0.15
    ports:
      - "6379:6379"
